# Generated by Django 4.0.4 on 2022-05-03 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='author',
            field=models.CharField(default='me', max_length=10),
        ),
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.CharField(default='all', max_length=10),
        ),
    ]
